In [ ]:
 !pip install folium geopandas scikit-learn

Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (0.20.0)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from folium) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium) (2026.3.0)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (26.1)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2026.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2026.4.22)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import folium

from folium.plugins import HeatMap
from sklearn.cluster import KMeans

In [ ]:
datos = {
    'lugar': [
        'Centro',
        'Portal del Quindio',
        'Universidad del Quindio',
        'Glorieta Malibu',
        'Hospital San Juan de Dios',
        'Coliseo del Cafe',
        'Centro',
        'Portal del Quindio',
        'Universidad del Quindio',
        'Glorieta Malibu'
    ],

    'latitud': [
        4.5350,
        4.5545,
        4.5551,
        4.5432,
        4.5338,
        4.5510,
        4.5362,
        4.5532,
        4.5561,
        4.5420
    ],

    'longitud': [
        -75.6757,
        -75.6581,
        -75.6615,
        -75.6725,
        -75.6811,
        -75.6670,
        -75.6765,
        -75.6590,
        -75.6622,
        -75.6730
    ],

    'trafico': [
        90,
        70,
        65,
        85,
        60,
        50,
        95,
        75,
        68,
        88
    ]
}

In [ ]:
df = pd.DataFrame(datos)

# Convertir tipos de datos
df['latitud'] = df['latitud'].astype(float)
df['longitud'] = df['longitud'].astype(float)
df['trafico'] = df['trafico'].astype(int)

df.head()

                       lugar  latitud  longitud  trafico
0                     Centro   4.5350  -75.6757       90
1         Portal del Quindio   4.5545  -75.6581       70
2    Universidad del Quindio   4.5551  -75.6615       65
3            Glorieta Malibu   4.5432  -75.6725       85
4  Hospital San Juan de Dios   4.5338  -75.6811       60

**Valor de tráfico**

| Valor  | Nivel |
| ------ | ----- |
| 0–40   | Bajo  |
| 41–70  | Medio |
| 71–100 | Alto  |

**Crear mapa interactivo**

In [ ]:
mapa = folium.Map(
    location=[4.543, -75.673],
    zoom_start=13
)

**Agregar puntos al mapa**

In [ ]:
mapa = folium.Map(
    location=[4.543, -75.673],
    zoom_start=13
)
for _, fila in df.iterrows():
    folium.CircleMarker(
        location=[
            float(fila['latitud']),
            float(fila['longitud'])
        ],
        radius=float(fila['trafico']) / 10,
        popup=f"Lugar: {fila['lugar']} - Trafico: {int(fila['trafico'])}",
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(mapa)
mapa

**Crear Mapa de Calor**

In [ ]:
datos_calor = [
    [
        float(fila['latitud']),
        float(fila['longitud']),
        float(fila['trafico'])
    ]
    for _, fila in df.iterrows()
]
mapa_calor = folium.Map(
    location=[4.543, -75.673],
    zoom_start=13
)
HeatMap(datos_calor).add_to(mapa_calor)
mapa_calor

**Mapa de Cluster**

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
X = df[['latitud', 'longitud', 'trafico']]

In [ ]:
kmeans = KMeans(
    n_clusters=3,
    random_state=42
)
df['cluster'] = kmeans.fit_predict(X)
df

                       lugar  latitud  longitud  trafico  cluster
0                     Centro   4.5350  -75.6757       90        0
1         Portal del Quindio   4.5545  -75.6581       70        1
2    Universidad del Quindio   4.5551  -75.6615       65        1
3            Glorieta Malibu   4.5432  -75.6725       85        0
4  Hospital San Juan de Dios   4.5338  -75.6811       60        2
5           Coliseo del Cafe   4.5510  -75.6670       50        2
6                     Centro   4.5362  -75.6765       95        0
7         Portal del Quindio   4.5532  -75.6590       75        1
8    Universidad del Quindio   4.5561  -75.6622       68        1
9            Glorieta Malibu   4.5420  -75.6730       88        0

In [ ]:
mapa_cluster = folium.Map(
    location=[4.543, -75.673],
    zoom_start=13
)
colores = {
    0: 'green',
    1: 'orange',
    2: 'red'
}
for _, fila in df.iterrows():
    cluster = int(fila['cluster'])
    folium.CircleMarker(
        location=[
            float(fila['latitud']),
            float(fila['longitud'])
        ],

        radius=10,
        popup=f"""
        Lugar: {fila['lugar']}
        Cluster: {cluster}
        Tráfico: {fila['trafico']}
        """,
        color=colores[cluster],
        fill=True,
        fill_color=colores[cluster],
        fill_opacity=0.7

    ).add_to(mapa_cluster)
mapa_cluster

- identifica patrones espaciales automáticamente
- clasifica zonas críticas
- detecta agrupamientos urbanos
- realiza análisis inteligente de movilidad

In [ ]:
for cluster in sorted(df['cluster'].unique()):
    promedio = df[df['cluster'] == cluster]['trafico'].mean()
    print(f"\nCLUSTER {cluster}")
    print(f"Promedio de tráfico: {promedio:.2f}")
    if promedio < 60:
        print("Nivel de congestión: BAJO")
    elif promedio < 80:
        print("Nivel de congestión: MEDIO")
    else:
        print("Nivel de congestión: ALTO")

CLUSTER 0
Promedio de tráfico: 89.50
Nivel de congestión: ALTO

CLUSTER 1
Promedio de tráfico: 69.50
Nivel de congestión: MEDIO

CLUSTER 2
Promedio de tráfico: 55.00
Nivel de congestión: BAJO

Mediante técnicas de clustering espacial utilizando el algoritmo K-Means, el sistema logró identificar agrupaciones territoriales asociadas a distintos niveles de congestión vehicular dentro de la ciudad de Armenia. Esto permitió detectar zonas críticas y sectores con comportamiento vial similar.